server:
  port: 8080

spring:
  application:
    name: tekflow-backend
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
